
service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30333

plugins: ""

grafana.ini:
  server:
    root_url: http://130.216.216.45:30333/
    domain: 130.216.216.45
  users:
    viewers_can_edit: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: dititaltwins-log
        type: loki
        url: http://loki.loki.svc.cluster.local:3100
        access: proxy
        isDefault: true
      - name: dititaltwins-metric
        type: prometheus
        url: http://mimir-gateway.mimir.svc.cluster.local/prometheus
        access: proxy