
service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30333

plugins: ""

grafana.ini:
  server:
    root_url: http://130.216.216.45:30333/
    domain: 130.216.216.45
  users:
    viewers_can_edit: true